name: moliseis
description: "La prima app multipiattaforma per il turismo in Molise."
publish_to: none

version: 2.2.0+101

environment:
  sdk: ^3.11.5

dependencies:
  # A
  animated_stateful_shell_route:
    git:
      url: https://github.com/xmattjus/animated_stateful_shell_route.git
      ref: 42462d3
  # B
  # C
  cached_network_image_ce: ^4.8.0
  collection: ^1.19.1
  cronet_http: ^1.6.0
  crypto: ^3.0.7
  cupertino_http: ^2.4.0
  cupertino_icons: ^1.0.9
  # D
  dart_mappable: ^4.8.0
  device_info_plus: ^13.1.0
  # E
  email_validator: ^3.0.0
  envied: ^1.3.5
  expressive_navigation_bar:
    git:
      url: https://github.com/xmattjus/expressive_navigation_bar.git
      ref: main
  # F
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.3.0
  # G
  go_router: ^17.3.0
  # H
  http: ^1.6.0
  # I
  image_picker: ^1.2.2
  intl: any
  # J
  # K
  # L
  latlong2: ^0.9.1
  # M
  markdown_widget: ^2.3.2+8
  material_color_utilities: ^0.13.0
  material_symbols_icons: ^4.2928.1
  meta: ^1.17.0
  # N
  # O
  objectbox: ^5.3.2
  objectbox_flutter_libs: ^5.3.2
  # P
  paged_vertical_calendar: ^1.1.10
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  # Q
  # R
  # S
  sentry: ^9.25.0
  sentry_flutter: ^9.25.0
  sentry_supabase: ^9.25.0
  share_plus: ^13.1.0
  skeletonizer: ^2.1.3
  smooth_page_indicator: ^2.0.1
  string_validator: ^1.2.0
  supabase: ^2.12.2
  supabase_flutter: ^2.14.2
  super_sliver_list: ^0.4.1
  swipe_image_gallery: ^0.11.0
  # T
  talker_flutter: ^5.1.17
  # U
  url_launcher: ^6.3.2
  # V
  very_good_analysis: ^10.2.0
  # W
  # X
  # Y
  # Z

dev_dependencies:
  # A
  # B
  build_runner: ^2.15.0
  # C
  # D
  # E
  dart_mappable_builder: ^4.8.0
  envied_generator: ^1.3.5
  # F
  file: ^7.0.1
  flutter_test:
    sdk: flutter
  # G
  # H
  # I
  # J
  # K
  # L
  # M
  mocktail: ^1.0.5
  # N
  # O
  objectbox_generator: ^5.3.2
  # P
  # Q
  # R
  # S
  # T
  # U
  # V
  # W
  # X
  # Y
  # Z

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Fraunces
      fonts:
        - asset: assets/fonts/Fraunces-VariableFont.ttf
        #- asset: assets/fonts/Fraunces-Italic-VariableFont.ttf
        #  style: italic
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-VariableFont.ttf

objectbox:
  # Writes objectbox-model.json and objectbox.g.dart to lib/generated (and test/generated).
  output_dir: generated
  # Or optionally specify the lib and test output folder separately.
  # output_dir:
  #   lib: custom
  #   test: other