name: moliseis
description: "La prima app multipiattaforma per il turismo in Molise."

publish_to: 'none'

version: 2.0.0+7

environment:
  sdk: ^3.8.1

dependencies:
  # A
  #animations: ^2.0.11
  # B
  # C
  cached_network_image: ^3.4.1
  cloudinary_api: ^1.1.1
  cloudinary_url_gen: ^1.8.0
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  # D
  device_info_plus: ^11.5.0
  #dynamic_color: ^1.7.0
  # E
  email_validator: ^3.0.0
  envied: ^1.2.0
  # F
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.2.1
  # G
  go_router: ^16.0.0 # '>=12.1.3 <13.0.0'
  # H
  http: ^1.5.0-beta.2
  # I
  image_picker: ^1.1.2
  intl: any
  # J
  json_annotation: ^4.9.0
  # K
  # L
  latlong2: ^0.9.1
  logging: ^1.3.0
  # M
  markdown_widget: ^2.3.2+8
  material_color_utilities: ^0.11.1
  # material_symbols_icons: ^4.2815.1
  meta: ^1.16.0
  # N
  # O
  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.3.0
  # P
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5
  # Q
  # R
  responsive_framework: ^1.5.1
  # result_dart: ^2.0.0
  # S
  sentry: ^9.6.0
  sentry_flutter: ^9.6.0
  sentry_logging: ^9.6.0
  share_plus: ^11.0.0
  skeletonizer: ^2.1.0+1
  string_validator: ^1.2.0
  supabase: ^2.8.0
  supabase_flutter: ^2.9.1
  swipe_image_gallery: ^0.10.2
  # T
  # U
  url_launcher: ^6.3.2
  # V
  # W
  # X
  # Y
  # Z

dev_dependencies:
  # A
  # B
  build_runner: ^2.5.4
  # C
  # D
  # E
  envied_generator: ^1.1.1
  # F
  #flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  # G
  # H
  # I
  # J
  json_serializable: ^6.9.5
  # K
  # L
  lint: ^2.8.0
  # M
  # N
  # O
  objectbox_generator: ^4.3.0
  # P
  # Q
  # R
  # S
  # T
  # U
  # V
  # W
  # X
  # Y
  # Z

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Fraunces
      fonts:
        - asset: assets/fonts/Fraunces-VariableFont.ttf
        #- asset: assets/fonts/Fraunces-Italic-VariableFont.ttf
        #  style: italic
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-VariableFont.ttf

objectbox:
  # Writes objectbox-model.json and objectbox.g.dart to lib/generated (and test/generated).
  output_dir: generated
  # Or optionally specify the lib and test output folder separately.
  # output_dir:
  #   lib: custom
  #   test: other