import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:moliseis/domain/models/attraction/attraction.dart';
import 'package:objectbox/objectbox.dart';

part 'place.g.dart';

@immutable
@Entity()
@JsonSerializable()
class Place {
  @Id(assignable: true)
  final int id;

  @Index()
  final String name;

  final String description;

  @Property(type: PropertyType.dateNano)
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @Property(type: PropertyType.dateNano)
  @JsonKey(name: 'modified_at')
  final DateTime modifiedAt;

  @Backlink()
  @_AttractionRelToManyConverter()
  final ToMany<Attraction> attractions;

  const Place({
    required this.id,
    required this.name,
    required this.description,
    required this.createdAt,
    required this.modifiedAt,
    required this.attractions,
  });

  @override
  bool operator ==(Object other) =>
      other is Place &&
      other.id == id &&
      other.name == name &&
      other.description == description &&
      other.createdAt.isAtSameMomentAs(createdAt) &&
      other.modifiedAt.isAtSameMomentAs(modifiedAt);

  @override
  int get hashCode => Object.hash(id, name, description, createdAt, modifiedAt);

  /// Creates a new [Place] from a Json string.
  ///
  /// The implementation of this method is generated by build_runner and
  /// the json_serializable package.
  factory Place.fromJson(Map<String, dynamic> json) => _$PlaceFromJson(json);

  /// Converts a [Place] to a Json string.
  ///
  /// The implementation of this method is generated by build_runner and
  /// the json_serializable package.
  Map<String, dynamic> toJson() => _$PlaceToJson(this);
}

class _AttractionRelToManyConverter
    implements JsonConverter<ToMany<Attraction>, List<Map<String, dynamic>>?> {
  const _AttractionRelToManyConverter();

  @override
  ToMany<Attraction> fromJson(List<Map<String, dynamic>>? json) =>
      ToMany<Attraction>(
        items: json?.map<Attraction>((e) => Attraction.fromJson(e)).toList(),
      );

  @override
  List<Map<String, dynamic>>? toJson(ToMany<Attraction> rel) =>
      rel.map((Attraction obj) => obj.toJson()).toList();
}
