import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:moliseis/domain/models/story/story.dart';
import 'package:objectbox/objectbox.dart';

part 'paragraph.g.dart';

@immutable
@Entity()
@JsonSerializable()
class Paragraph {
  @Id(assignable: true)
  final int id;

  final String heading;

  final String subheading;

  final String body;

  @JsonKey(name: 'story_id')
  final int backlinkId;

  @Property(type: PropertyType.dateNano)
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @Property(type: PropertyType.dateNano)
  @JsonKey(name: 'modified_at')
  final DateTime modifiedAt;

  @_StoryRelToOneConverter()
  final ToOne<Story> story;

  const Paragraph({
    required this.id,
    required this.heading,
    required this.subheading,
    required this.body,
    required this.backlinkId,
    required this.createdAt,
    required this.modifiedAt,
    required this.story,
  });

  @override
  bool operator ==(Object other) =>
      other is Paragraph &&
      other.id == id &&
      other.heading == heading &&
      other.subheading == subheading &&
      other.body == body &&
      other.backlinkId == backlinkId &&
      other.createdAt.isAtSameMomentAs(createdAt) &&
      other.modifiedAt.isAtSameMomentAs(modifiedAt);

  @override
  int get hashCode => Object.hash(
    id,
    heading,
    subheading,
    body,
    backlinkId,
    createdAt,
    modifiedAt,
  );

  /// Creates a new [Paragraph] from a Json string.
  ///
  /// The implementation of this method is generated by build_runner and
  /// the json_serializable package.
  factory Paragraph.fromJson(Map<String, dynamic> json) =>
      _$ParagraphFromJson(json);

  /// Converts a [Paragraph] to a Json string.
  ///
  /// The implementation of this method is generated by build_runner and
  /// the json_serializable package.
  Map<String, dynamic> toJson() => _$ParagraphToJson(this);
}

class _StoryRelToOneConverter
    implements JsonConverter<ToOne<Story>, Map<String, dynamic>?> {
  const _StoryRelToOneConverter();

  @override
  ToOne<Story> fromJson(Map<String, dynamic>? json) =>
      ToOne<Story>(target: json == null ? null : Story.fromJson(json));

  @override
  Map<String, dynamic>? toJson(ToOne<Story> rel) => rel.target?.toJson();
}
